#!/usr/bin/env python3
# vim: set noexpandtab tabstop=2 shiftwidth=2 softtabstop=-1 fileencoding=utf-8:

import os
import sys
from exeR.exeR import exeR
from pathlib import Path
import random
import socket
import click

CONTEXT_SETTINGS=dict(help_option_names=['-h', '--help'])
@click.command(context_settings=CONTEXT_SETTINGS)
@click.option('-d', '--outdir', type=click.Path(resolve_path=True), default='.', show_default=True, help='Outdir.')
@click.option('-b', '--bname', type=click.STRING, required=True, help='Bname.')
@click.option('-e', '--condaenv', type=click.STRING, help='Conda environment.')
@click.option('-g', '--group', type=click.STRING, multiple=True, required=True, help='Group to plot the UMAP.')
@click.option('-s', '--split', type=click.STRING, required=True, help='Split name.')
@click.option('-H', '--height', type=click.FLOAT, default=6, show_default=True, help='Height.')
@click.option('-W', '--width', type=click.FLOAT, default=6, show_default=True, help='Width.')
@click.option('-L', '--legendwidth', type=click.FLOAT, default=1, show_default=True, help='Legend width.')
@click.option('-t', '--showtitle', type=click.Choice(['F', 'T']), is_flag=False, flag_value='F', default='T', show_default=True, help='Keep plot title.')
@click.option('-f', '--format', type=click.Choice(['pdf', 'png']), is_flag=False, flag_value='pdf', default='png', show_default=True, help='Image format.')
@click.argument('infile', type=click.Path(exists=True, resolve_path=True))
def main(outdir, bname, condaenv, group, split, height, width, legendwidth, showtitle, format, infile):
	"""
Plot UMAP by Seurat DimPlot() for split.by function.

INFILE is a SATURN UMAP file (.h5ad).

\b
Example:
  f=/storage/singlecell/jinli/wkfl/atlashumanprj/integration/snRNA/cross_species/saturncrossspecieswkfl/BC/s2k/saturntrainh5ad2umap/BC_mouse_macaque/BC_mouse_macaque.h5ad
  outdir=$(mrrdir.sh)
  bname=$(basename "$f" .h5ad)
  slurmtaco.sh -t 2 -m 20G -- saturnh5adumap2seuratdimplotsplitby -d "$outdir" -b "$bname" -e saturn -g labels -g labels2 -g ref_labels -s species -- "$f"

\b
Note:
  1. The .h5ad file is generated by anndata>=0.8.0, which is hard-coded by SATURN. So, stick to the structure of the new .h5ad file.

\b
See also:
  Related:
    scrnaseuratumapby.sh
  Depends:
    R/rhdf5
    R/Seurat

\b
Date: 2023/03/06
Authors: Jin Li <lijin.abc@gmail.com>
	"""
	absdir=Path(__file__).parent
	scriptname=Path(__file__).stem
	script=f'{absdir}/R/{scriptname}.R'
	exprs=[
		f"outdir='{outdir}'",
		f"bname='{bname}'",
		f"group=c({str(list(group))[1:-1] if group is not None else ''})",
		f"split='{split}'",
		f"height={height}",
		f"width={width}",
		f"legendwidth={legendwidth}",
		f"showtitle={showtitle}",
		f"format='{format}'",
		f"infile='{infile}'",
		]
	Path(outdir).mkdir(parents=True, exist_ok=True)
	# os.chdir(outdir)
	return exeR.callback(exprs, script=script, condaenv=condaenv, verbose=True)

if __name__ == "__main__":
	sys.exit(main())
