#!/usr/bin/env python3
# vim: set noexpandtab tabstop=2 shiftwidth=2 softtabstop=-1 fileencoding=utf-8:

import os
import sys
from exeR.exeR import exeR
from pathlib import Path
import random
import socket
import click

CONTEXT_SETTINGS=dict(help_option_names=['-h', '--help'])
@click.command(context_settings=CONTEXT_SETTINGS)
@click.option('-d', '--outdir', type=click.Path(resolve_path=True), default='.', show_default=True, help='Outdir.')
@click.option('-b', '--bname', type=click.STRING, required=True, help='Bname.')
@click.option('-e', '--condaenv', type=click.STRING, help='Conda environment.')
@click.option('-g', '--group', type=click.STRING, default='labels', show_default=True, help='Group for clusters.')
@click.option('-c', '--color', type=click.STRING, default='species', show_default=True, help='Color label.')
@click.option('-r', '--reorder', type=click.Choice(['F', 'T']), is_flag=False, flag_value='T', default='F', show_default=True, help='Factor reordering of cell clusters.')
@click.option('-n', '--numericorder', type=click.Choice(['F', 'T']), is_flag=False, flag_value='T', default='F', show_default=True, help='Assign numeric value to cluster IDs. (Only effective for `-r|--reorder`).')
@click.option('-H', '--height', type=click.FLOAT, default=7.5, show_default=True, help='Height.')
@click.option('-W', '--width', type=click.FLOAT, default=6, show_default=True, help='Width.')
@click.argument('infile', type=click.Path(exists=True, resolve_path=True))
def main(outdir, bname, condaenv, group, color, reorder, numericorder, height, width, infile):
	"""
Build and plot a phylogenetic tree using SATURN low-embedding for cross-species.

INFILE is a SATURN UMAP file (.h5ad).

\b
Example:
  f=/storage/singlecell/jinli/wkfl/atlashumanprj/integration/snRNA/cross_species/saturncrossspecieswkfl/BC/s2k/saturntrainh5ad2umap/BC_mouse_macaque/BC_mouse_macaque.h5ad
  outdir=$(mrrdir.sh)
  bname=$(basename "$f" .h5ad)
  slurmtaco.sh -t 2 -m 20G -- saturnh5adumap2seuratclustree -d "$outdir" -b "$bname" -e saturn -g labels -c species -- "$f"

\b
Note:
  1. The .h5ad file is generated by anndata>=0.8.0, which is hard-coded by SATURN. So, stick to the structure of the new .h5ad file.

\b
See also:
  Related:
    saturnh5adumap2seuratdimplotsplitby
  Depends:
    R/rhdf5
    R/Seurat
    R/ape

\b
Date: 2023/03/09
Authors: Jin Li <lijin.abc@gmail.com>
	"""
	absdir=Path(__file__).parent
	scriptname=Path(__file__).stem
	script=f'{absdir}/R/{scriptname}.R'
	exprs=[
		f"outdir='{outdir}'",
		f"bname='{bname}'",
		f"group='{group}'",
		f"color='{color}'",
		f"reorder={reorder}",
		f"numericorder={numericorder}",
		f"height={height}",
		f"width={width}",
		f"infile='{infile}'",
		]
	Path(outdir).mkdir(parents=True, exist_ok=True)
	# os.chdir(outdir)
	return exeR.callback(exprs, script=script, condaenv=condaenv, verbose=True)

if __name__ == "__main__":
	sys.exit(main())
